kind: Deployment
apiVersion: apps/v1
metadata:
  name: amq-broker
  labels:
    app: amq-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amq-broker
  template:
    metadata:
      labels:
        app: amq-broker
    spec:
      containers:
        - name: amq-broker
          image: 'registry.redhat.io/amq7/amq-broker-rhel8:7.11'
          ports:
            - name: amq-broker
              containerPort: 61616
              protocol: TCP
          env:
            - name: AMQ_USER
              value: admin
            - name: AMQ_PASSWORD
              value: admin
            - name: AMQ_REQUIRE_LOGIN
              value: 'true'
